### PR TITLE
Fix: customize message for blank select values

### LINKED ISSUE #638: Customize message for blank select values in Forms
## Description
- Customize message for blank select values in Forms
- Right now all fields in forms use the same error message if blank

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/landscapes/[landscape slug]/edit
2. Clear value in country select
3.  Watch error message

## Expected behavior
The message for empty Select should be different than other fields

## Actual behavior
The same message appear for all fields when the value is required

## Additional context

image

### PR DESCRIPTION
**Pull request by jodiezhuu**
## Description
yup.setLocale section is modified to include a condition based on the path parameter in the required method

### Checklist
- [X] Customize message for blank select values in Forms

### Related Issues
Fixes #638 

### Verification steps
1. Go to URL: https://app.staging.terraso.net/landscapes/[landscape slug]/edit
2. Clear value in country select
3. Watch error message

### CODE REVIEW

**Comment by jodiezhuu** [comment]
Not sure if this is the best solution for #638;

Another possible solution: Introduce a `selected` localization method, which is similar to `required` but specifically for selection/dropdown components; an advantage of this could be that the validation schema is more organized and we could avoid adding more conditions to `required` in the future (if we wish to customize an error message for another component). 

Would love to hear any other ideas!

File: src/forms/yup.js [hunk 1]
```diff
@@ -24,7 +24,11 @@ const ARRAY_INDEX_REGEX = /\[([^)]+)\]/;
 yup.setLocale({
   mixed: {
     default: params => ({ key: 'form.validation_field_invalid', params }),
-    required: params => ({ key: 'form.validation_field_required', params }),
+    required: params => {
+      return params.path === 'location'
```
Comment (paulschreiber) [inline src/forms/yup.js:28]: question: does this only work for the field named `location`? We want it to work for any <select>.

Comment (josebui) [inline src/forms/yup.js:28]: Issue: `yup.js` ideally should not be aware of what `location` is. I think for this you should be able to define a custom required message for the specific validation:
https://github.com/techmatters/terraso-web-client/blob/main/src/landscape/components/LandscapeForm/KeyInfoStep.js#LL41C23-L41C46
```
location: yup.string().trim().required(),
```
Maybe something like this:
```
location: yup.string().trim().required(params => ({ key: 'form.validation_select_field_required', params })),
```

**Review by josebui — CHANGES_REQUESTED** [review]

File: src/forms/yup.js (hunk 1 above)
Comment (jodiezhuu) [reply src/forms/yup.js]: Just added a custom validation rule just for selected that can be added to any validation schema

File: src/forms/yup.js [hunk 2]
```diff
@@ -19,16 +19,27 @@ import * as yup from 'yup';
...
+  return true;
+};
+
+yup.addMethod(yup.string, 'selected', function () {
+  return this.test(
+    'selected',
+    params => ({ key: 'form.validation_select_field_required', params }),
+    value => isCountrySelected(value)
+  );
+});
```
Comment (paulschreiber) [inline src/forms/yup.js:35]: @josebui would it make sense to use an arrow function here?

File: src/forms/yup.js [hunk 3]
```diff
@@ -19,16 +19,27 @@ import * as yup from 'yup';
 
 const ARRAY_INDEX_REGEX = /\[([^)]+)\]/;
 
+const isCountrySelected = value => {
+  if (!value || value === '') {
+    return false;
+  }
+  return true;
+};
```
Comment (paulschreiber) [inline src/forms/yup.js:27]: suggestion: remove this function

File: src/forms/yup.js [hunk 4]
```diff
@@ -19,16 +19,27 @@ import * as yup from 'yup';
...
+
+yup.addMethod(yup.string, 'selected', function () {
+  return this.test(
+    'selected',
+    params => ({ key: 'form.validation_select_field_required', params }),
+    value => isCountrySelected(value)
```
Comment (paulschreiber) [inline src/forms/yup.js:33]: suggestion: Use something like `value => Boolean(value)`

**Review by paulschreiber — CHANGES_REQUESTED** [review]

File: src/forms/yup.js (hunk 4 above)
Comment (jodiezhuu) [reply src/forms/yup.js:33]: Thanks! Didn't know that was a built in function

File: src/landscape/components/LandscapeForm/KeyInfoStep.js [hunk 5]
```diff
@@ -38,7 +38,7 @@ const VALIDATION_SCHEMA = yup
   .object({
     name: yup.string().trim().required(),
     description: yup.string().max(MAX_DESCRIPTION_LENGTH).trim().required(),
-    location: yup.string().trim().required(),
+    location: yup.string().trim().selected().required(),
```
Comment (josebui) [inline src/landscape/components/LandscapeForm/KeyInfoStep.js:41]: Question: Do we need selected() and required() too? it seems that selected is a customized required check

File: src/forms/yup.js [hunk 6]
```diff
@@ -19,6 +19,14 @@ import * as yup from 'yup';
 
 const ARRAY_INDEX_REGEX = /\[([^)]+)\]/;
 
+yup.addMethod(yup.string, 'selected', function () {
+  return this.test(
+    'selected',
+    params => ({ key: 'form.validation_select_field_required', params }),
+    value => Boolean(value)
```
Comment (josebui) [inline src/forms/yup.js:26]: Suggestion: I don't think we need to define a new way to check if something is required, I think you should be able to use required() inside this and define the custom message, something like: 
```javascript
yup.addMethod(yup.string, 'selected', function () {
  return this.required(params => ({
    key: 'form.validation_select_field_required',
    params,
  }));
});
```

File: src/forms/yup.js (hunk 2 above)
Comment (josebui) [reply src/forms/yup.js]: @paulschreiber you mean instead of `'selected', function () {`? If you see there yup expects the use of `this` inside it, so we have to use `function() {}` to be able to use that binded this

**Review by josebui — APPROVED** [review]

**Review by paulschreiber — APPROVED** [review]

**Comment by paulschreiber** [comment]
@jodiezhuu Please look over the forms and see if other pages also need to be updated to use the new `selected()` method.
