### PR TITLE
fix: replace theme.spacing(XYZ) with XYZ

### LINKED ISSUE #931: Remove theme.spacing from code
## Description
In the code, `replace theme.spacing(XYZ)` with `XYZ`.

### PR DESCRIPTION
**Pull request by jodiezhuu**
## Description
Replaced `theme.spacing(XYZ)` with `XYZ` in codebase

### Related Issues
Fixes #931

### CODE REVIEW

File: src/account/components/AccountLogin.js [hunk 1]
```diff
@@ -70,7 +68,7 @@ const AccountForm = () => {
       direction="column"
       alignItems="center"
       justifyContent="center"
-      style={{ height: '80vh', margin: `auto ${theme.spacing(2)}` }}
+      style={{ height: '80vh', margin: `auto ${2}` }}
```
Comment (paulschreiber) [inline src/account/components/AccountLogin.js:71]:
```suggestion
      style={{ height: '80vh' }}
```

**Review by paulschreiber — APPROVED** [review]
Looks good. Made one suggestion in GitHub and pushed one change.

File: src/common/components/RichTextEditor/index.js [hunk 2]
```diff
@@ -515,8 +513,8 @@ const RichTextEditor = props => {
           style={
             addContainer
               ? {
-                  paddingLeft: theme.spacing(2),
-                  paddingRight: theme.spacing(2),
+                  paddingLeft: 2,
```
Comment (josebui) [inline src/common/components/RichTextEditor/index.js:516]: Issue: You can only use the mui spacing values directly inside mui components, this is not an MUI component, this should stay the same

File: src/common/components/UnexpectedError.js [hunk 3]
```diff
@@ -35,7 +35,7 @@ const UnexpectedError = () => {
       <Stack
         component={Paper}
         elevation={0}
-        sx={theme => ({ maxWidth: 'md', padding: theme.spacing(3) })}
+        sx={theme => ({ maxWidth: 'md', padding: 3 })}
```
Comment (josebui) [inline src/common/components/UnexpectedError.js:38]: Issue: The `theme` variable is not used anymore, it can be removed

File: src/common/components/UnexpectedError.js [hunk 4]
```diff
@@ -32,12 +32,7 @@ const UnexpectedError = () => {
       justifyContent="center"
       sx={{ height: '80vh' }}
     >
-      <Stack
-        component={Paper}
-        elevation={0}
-        sx={theme => ({ maxWidth: 'md', padding: 3 })}
-        alignItems="center"
-      >
+      <Stack component={Paper} elevation={0} alignItems="center">
```
Comment (paulschreiber) [inline src/common/components/UnexpectedError.js:35]: issue: you removed the spacing entire. Please apply Jose's suggestion.

**Review by paulschreiber — CHANGES_REQUESTED** [review]

File: src/common/components/UnexpectedError.js (hunk 4 above)
Comment (paulschreiber) [reply src/common/components/UnexpectedError.js:35]: Looks like something got mangled during the merge/change. The only lime that should change is
```
        sx={theme => ({ maxWidth: 'md', padding: theme.spacing(3) })}
```

Comment (jodiezhuu) [reply src/common/components/UnexpectedError.js]: sorry about that, my revert was a bit buggy; should be fixed now

**Review by paulschreiber — APPROVED** [review]

File: src/common/components/TableResponsive.js [hunk 5]
```diff
@@ -126,16 +126,13 @@ const Cards = props => {
...
-          sx={theme => ({ padding: 0, marginBottom: theme.spacing(2) })}
-        >
+        <ListItem key={row.id} sx={theme => ({ padding: 0, marginBottom: 2 })}>
           <Card
             component={Stack}
             direction="row"
             alignItems="center"
             spacing={1}
-            sx={theme => ({ width: '100%', padding: theme.spacing(2) })}
+            sx={theme => ({ width: '100%', padding: 2 })}
```
Comment (josebui) [inline src/common/components/TableResponsive.js:135]:
```suggestion
            sx={{ width: '100%', padding: 2 }}
```

File: src/layout/PageHeader.js [hunk 6]
```diff
@@ -23,7 +23,7 @@ const PageHeader = ({ header, children, typographyProps = {} }) => (
     variant="h1"
     tabIndex="-1"
     id="main-heading"
-    sx={theme => ({ marginBottom: theme.spacing(3) })}
+    sx={theme => ({ marginBottom: 3 })}
```
Comment (josebui) [inline src/layout/PageHeader.js:26]:
```suggestion
    sx={{ marginBottom: 3 }}
```

**Review by josebui — APPROVED** [review]
Looks good
