### PR TITLE
fix: fix layout bugs with increased magnification; update Spanish translation

### LINKED ISSUE #1127: Bread crumb for "Terraso Story Maps" reads, "Terraso Story Map"
## Description
The bread crumb for the page "Terraso Story Maps" does not match the page title.

## Steps To Reproduce
1. Go to URL: https://app.terraso.org/tools/story-maps/3tlzj2i/rocky-hill-sustainability
2. See issue

## Expected behavior
bread crumb should read "Home/Tools/Terraso Story Maps"

## Actual behavior
bread crumb reads "Home/Tools/Terraso Story Map"

image

### LINKED ISSUE #1143: On home screen, with high zoom, the Kobo text expands past the card
## Steps To Reproduce

1. log into app.terraso.org
2. zoom in screen to 125%

## Expected behavior
Card expands to fit contain the text

## Actual behavior
Text goes beyond the card

image

### LINKED ISSUE #1144: Spanish home screen uses outdated story maps graphic
## Description
As a user with a Spanish UI, the Story Maps icon shows up on the home page instead of the screenshot image

## Steps To Reproduce
1. Log into terraso and go to home page.
2. Look at story maps card
3. see issue

## Expected behavior
card uses screenshot image visible on English site (with spanish language overlay) 
image
Image: https://app.terraso.org/static/media/story-maps.6b585d3df108e6514844.png

## Actual behavior
Card uses terraso story maps icon
image

### PR DESCRIPTION
**Pull request by paulschreiber**
## Description
- When the font size is increased, correctly render:
-- KoboToolbox home card
-- data maps point size slider
- Fix and breadcrumbs for Story Maps
- Update art for Story Maps card in Spanish
- Correctly wrap text on Story Map card image

before:
image

after:
image

### Related Issues
Fixes #1143, Fixes #1127, Fixes #1144

### CODE REVIEW

File: src/home/components/HomeCard.js [hunk 1]
```diff
@@ -94,7 +94,8 @@ const HomeCard = ({
                     background: 'transparent',
                     position: 'absolute',
                     bottom: 1,
-                    pl: 4.5,
+                    right: 4.5,
+                    paddingRight: 1,
```
Comment (josebui) [inline src/home/components/HomeCard.js:98]:
```suggestion
                    pr: 1,
```

File: src/sharedData/visualization/components/VisualizationConfigForm/VisualizeStep.js [hunk 2]
```diff
@@ -109,6 +109,7 @@ const Size = props => {
             step: 1,
             min: 5,
             max: 30,
+            sx: { padding: 1 },
```
Comment (josebui) [inline src/sharedData/visualization/components/VisualizationConfigForm/VisualizeStep.js:112]:
```suggestion
            sx: { p: 1 },
```

**Review by josebui — APPROVED** [review]
Looks good, just 2 suggestions

**Review by josebui — APPROVED** [review]
