### PR TITLE
fix: shared files message

### LINKED ISSUE #367: Shared File module message when no files shared vs. 1 or more files are shared
## Description
Users need to know how to use Shared Files module before uploading files; file type, who has access to them, etc. 
The current message doesn't support the 0 file case well. 

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: '[...](https://app.staging.terraso.org/landscapes/new-landscape-52622)'
2. Scroll down to 'SHARED FILES' module
4. See  the UI copy above 'Share Files' button

## Expected behavior
UC. If 0 files are shared in Shared Files module, display 'Upload your data files (*.xls, *.xlsx,*.csv) and share them with the [group/landscape] members. Only the members can download the files. Read more about sharing files.' above the Share files button. 
image

UC. If 1 or more files are shared, display 'Only the members of your group can download the files. [Read more about sharing files](http://terraso.org/help/sharing-files/).' 
image

## Actual behavior
Regardless the number of shared file, the same message is displayed. 
[UC: 0 file shared]
image

[UC: 1 file shared]
image

### PR DESCRIPTION
**Pull request by paulschreiber**
## Description
On the shared data card, show different messages if files are/are not present.

### Checklist
- [X] Corresponding issue has been opened
- [X] English strings reviewed and copyedited
- [x] Strings are localized

### Related Issues
Fixes #367.

### Verification steps
Open a landscape for which you are a member (and there are files).
Open a landscape for which you are a member (and there are no files).
Open a group for which you are a member (and there are files).
Open a group for which you are a member (and there are no files).

image

image

### CODE REVIEW

File: src/sharedData/components/SharedDataCard.js [hunk 1]
```diff
@@ -38,7 +39,7 @@ const EntriesList = withProps(List, {
 
 const SharedFilesCard = props => {
   const { t } = useTranslation();
-  const { onUploadClick } = props;
+  const { onUploadClick, name } = props;
```
Comment (josebui) [inline src/sharedData/components/SharedDataCard.js:42]: Issue: You should use `owner` from  `useGroupContext()` to get the name

**Review by josebui — CHANGES_REQUESTED** [review]

File: src/localization/locales/es-ES.json [hunk 2]
```diff
@@ -270,7 +270,8 @@
     },
     "shared_data": {
         "title": "Archivos compartidos",
-        "description": "Solo los miembros de tu grupo pueden descargar los archivos. <1>Más información sobre cómo compartir archivos</1>.",
+        "description_with_files": "Solo los miembros de tu grupo pueden descargar los archivos. <1>Más información sobre cómo compartir archivos</1>.",
+        "description_without_files": "[TODO]Upload your data files ({{extensions}}) and share them with the {{group}} members. Solo los miembros de tu grupo pueden descargar los archivos. <1>Más información sobre cómo compartir archivos</1>.",
```
Comment (josebui) [inline src/localization/locales/es-ES.json:274]:
```suggestion
        "description_without_files": "Sube tus archivos de datos ({{extensions}}) y compártelos con los miembros del {{group}}. Solo los miembros de tu grupo pueden descargar los archivos. <1>Más información sobre cómo compartir archivos</1>.",
```
