### PR TITLE
fix: Improved accessibility for home lists

### LINKED ISSUE #202: Accessibility: Fix nested list for Groups and Landsacpes in Home page
## Description
Landscape and group elements in the Home dashboard are indentified as list elements in the markup, this is affecting the accessibility of the page

### PR DESCRIPTION
**Pull request by josebui**
## Description

- Improved home lists accessibility
- Added home sections
- Added global lint command

### Checklist
- [x] Corresponding issue has been opened
- [ ] New tests added
- [ ] Strings are localized
- [x] Verified on mobile
- [x] Verified on desktop
- [x] Verified accessibility ([Accessibility - Web applications](https://docs.google.com/document/d/1VwPDyLqw7r_iISMgDZr1FdAmAqqOIIVIxQqsYA-HaHE/edit?usp=sharing))

### Related Issues
Fixes #202

### CODE REVIEW

File: src/group/components/GroupsHomeCard.js [hunk 1]
```diff
@@ -18,34 +18,44 @@ import theme from 'theme';
...
       <Link
         component={RouterLink}
         underline="none"
         to={`/groups/${group.slug}`}
       >
         {group.name}
       </Link>
-      &nbsp;({t(`group.role_${_.getOr('member', 'role', group)}`)})
-    </List>
+      &nbsp;
```
Comment (paulschreiber) [inline src/group/components/GroupsHomeCard.js:29]: question: this this to prevent a word wrap or to add whitespace? Can we uses CSS instead?

Comment (josebui) [reply src/group/components/GroupsHomeCard.js:29]: @paulschreiber I think it was added to add the space (i don't remeber if I did this). I can use `theme.spacing()` to keep it consistent with the rest of the code

**Review by cacarrara — APPROVED** [review]
LGTM and I agree with Paul's comment.
