### PR TITLE
fix: Disable link on logo when on home page

### LINKED ISSUE #294: Disable link on logo when on home page
## Description
Currently, the Terraso logo links to the home page. When we are already on the home page, the logo should not be clickable.

### PR DESCRIPTION
**Pull request by paulschreiber**
## Description
Disables the link on the logo when on home page (don't self-link).

### Checklist
- [X] Corresponding issue has been opened
- [X] Verified on mobile
- [X] Verified on desktop

### Related Issues
Fixes #294.

### CODE REVIEW

File: src/common/components/ConditionalLink.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import { Link } from 'react-router-dom';
+
+const ConditionalLink = ({ children, to, condition }) => {
+  if (!!condition && to) {
+    return <Link to={to}>{children}</Link>;
+  } else {
+    return <>{children}</>;
+  }
```
Comment (josebui) [inline src/common/components/ConditionalLink.js:8]: Suggestion: This feels easier to read for me
```suggestion
  return (!!condition && to)
    ? <Link to={to}>{children}</Link>
    : <>{children}</>;
```

File: src/common/components/ConditionalLink.js [hunk 2]
```diff
@@ -0,0 +1,11 @@
+import { Link } from 'react-router-dom';
+
+const ConditionalLink = ({ children, to, condition }) => {
+  if (!!condition && to) {
+    return <Link to={to}>{children}</Link>;
+  } else {
+    return <>{children}</>;
```
Comment (josebui) [inline src/common/components/ConditionalLink.js:7]: Question: Should this be wrapped by `Typography`? I think it will be just text directly in the markup without it.

Comment (paulschreiber) [reply src/common/components/ConditionalLink.js:7]: Not necessarily. In this case, I have an image, which doesn't need a wrapper.

File: src/common/components/ConditionalLink.js (hunk 1 above)
Comment (paulschreiber) [reply src/common/components/ConditionalLink.js:8]: The [Stack Overflow answer](https://stackoverflow.com/a/56278522) had a ternary, but I found it to be overly dense/harder to follow. Spreading it out is more readable and will make debugging easier.

**Review by josebui — APPROVED** [review]
