### PR TITLE
fix: use "landscape" or "group" as appropriate on shared data card

### LINKED ISSUE #391: Shared Files UI text in Landscape says '.... group....'
## Description
Shared Files UI text in Landscape should say '.... landscape ....' instead of .... group....'

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: https://app.staging.terraso.org/landscapes/cobiocom OR any landscape with a shared file. 
2. Scroll down to Share Files module
4. See the UI text below the file. 

## Expected behavior
image

## Actual behavior
image

### PR DESCRIPTION
**Pull request by paulschreiber**
## Description
Update the shared files card to use "landscape" or "group" as appropriate (and not just "group").

### Checklist
- [X] Corresponding issue has been opened
- [X] English strings reviewed and copyedited
- [X] Strings are localized

### Related Issues
Fixes #391.

### CODE REVIEW

File: src/sharedData/components/SharedDataCard.js [hunk 1]
```diff
@@ -86,6 +86,9 @@ const SharedFilesCard = props => {
                   ext => `*.${ext}`
                 ).join(', '),
                 name: owner.name,
+                item: owner.defaultGroup
```
Comment (josebui) [inline src/sharedData/components/SharedDataCard.js:89]: Suggestion: `type` feels a little less generic than `item`, I don't think `item` is telling me anything about the data, maybe even `entityType`?

File: src/localization/locales/es-ES.json [hunk 2]
```diff
@@ -271,7 +271,9 @@
     },
     "sharedData": {
         "title": "Archivos compartidos",
-        "description_with_files": "Solo los miembros de tu grupo pueden descargar los archivos. <1>Más información sobre cómo compartir archivos</1>.",
+        "description_with_files": "Solo los miembros de tu {{entityType}} pueden descargar los archivos. <1>Más información sobre cómo compartir archivos</1>.",
+        "item_group": "groupo",
```
Comment (josebui) [inline src/localization/locales/es-ES.json:275]: Suggestion:
```suggestion
        "entity_type_group": "grupo",
```

**Review by cacarrara — APPROVED** [review]
