### PR TITLE
fix: scroll to top between steps when creating landscapes

### LINKED ISSUE #397: Uploading map boundary screens doesn't show the page title on load
## Description
In the creating landscape workflow, two screens of uploading the map boundary didn't scroll up when user tap Next button. 

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: https://app.terraso.org/landscapes/new in tiny viewport 
2. Fill the form and tap 'Next'
4. Notice the screen is showing the bottom half of the screen in the viewport 

## Expected behavior
The top portion of the screen in the viewport. 

## Actual behavior
image

**Geojson file update screen**
image

### PR DESCRIPTION
**Pull request by paulschreiber**
## Description
When creating a landscape, scroll to the top of the viewport after each step.

### Checklist
- [X] Corresponding issue has been opened
- [X] Verified on mobile
- [X] Verified on desktop

### Related Issues
Fixes #397.

### CODE REVIEW

File: src/landscape/components/LandscapeForm/BoundaryStep.js [hunk 1]
```diff
@@ -160,7 +160,10 @@ const BoundaryOptions = props => {
             key={index}
             fullWidth
             variant="outlined"
-            onClick={option.onClick}
+            onClick={() => {
```
Comment (josebui) [inline src/landscape/components/LandscapeForm/BoundaryStep.js:163]: Suggestion: Move the on click handler outside of the markup, I think it is more readable if you have more than one action performing here to move it outside

File: src/landscape/components/LandscapeForm/InfoStep.js [hunk 2]
```diff
@@ -117,6 +122,7 @@ const InfoStep = props => {
         validationSchema={VALIDATION_SCHEMA}
         onSave={updatedLandscape => {
           setUpdatedLandscape(updatedLandscape);
```
Comment (josebui) [inline src/landscape/components/LandscapeForm/InfoStep.js:124]: Suggestion: Same here
