### PR TITLE
fix: Improved Trans values and MUI Avatar allowed props validation

### LINKED ISSUE #466: Test warning: Failed prop type error in GroupMembershipCard.js
## Description
When running tests, we get this error:
```
    console.error
      Warning: Failed prop type: Invalid prop `children` supplied to `ForwardRef(Typography)`, expected a ReactNode.
          at Typography (/home/runner/work/terraso-web-client/terraso-web-client/node_modules/@mui/material/node/Typography/Typography.js:108:49)
```

It is likely due to line 81 in GroupMembershipCard.js:
```
            {{ name: owner.name }} description
```

### LINKED ISSUE #497: Test warnings due to Avatar changes
## Description
The commit https://github.com/techmatters/terraso-web-client/commit/7835a7d436ed7d7dfc22d5159238629b23d02ed9 introduced a two warnings that appear during testing:

```
    console.error
      Warning: Failed prop type: Invalid prop `imgProps` of type `boolean` supplied to `ForwardRef(Avatar)`, expected `object`.
          at Avatar (/home/runner/work/terraso-web-client/terraso-web-client/node_modules/@mui/material/node/Avatar/Avatar.js:161:44)
          at AccountAvatar (/home/runner/work/terraso-web-client/terraso-web-client/src/account/components/AccountAvatar.js:8:11)
          at ProfilePicture (/home/runner/work/terraso-web-client/terraso-web-client/src/account/components/AccountProfile.js:78:26)
          at FormFieldInput (/home/runner/work/terraso-web-client/terraso-web-client/src/forms/components/FormField.js:16:11)

   ...

    console.error
      Warning: React does not recognize the `showAlt` prop on a DOM element. If you intentionally want it to
      appear in the DOM as a custom attribute, spell it as lowercase `showalt` instead. If you accidentally passed
      it from a parent component, remove it from the DOM element.
```

### PR DESCRIPTION
**Pull request by josebui**
## Description

- Improved Trans component values if used with Typography MUI component
- Added Avatar validation for allowed props 

### Checklist
- [x] Corresponding issue has been opened
- [ ] New tests added
- [ ] English strings reviewed and copyedited
- [ ] Strings are localized
- [ ] Verified on mobile
- [ ] Verified on desktop
- [ ] Verified accessibility ([Accessibility - Web applications](https://docs.google.com/document/d/1VwPDyLqw7r_iISMgDZr1FdAmAqqOIIVIxQqsYA-HaHE/edit?usp=sharing))

### Related Issues
Fixes #497 
Fixes #466

### CODE REVIEW

File: src/account/components/AccountAvatar.js [hunk 1]
```diff
@@ -8,17 +8,27 @@ const AccountAvatar = props => {
...
+    'children',
+    'classes',
+    'className',
+    'component',
+    'imgProps',
+    'sizes',
+    'src',
+    'srcSet',
+    'sx',
+    'variant',
```
Comment (paulschreiber) [inline src/account/components/AccountAvatar.js:22]: question: should include ID? or will that work without being in the list?

**Review by paulschreiber — APPROVED** [review]

File: src/account/components/AccountAvatar.js (hunk 1 above)
Comment (josebui) [reply src/account/components/AccountAvatar.js:22]: @paulschreiber this will omit ID if it is sent, I checked and right now we are not passing ID to the AccountAvatar component, so I think we can leave it there and if is needed we can add it
