### PR TITLE
fix: Data map annotate step fixes

### LINKED ISSUE #1150: when customizing the data labels in data maps, input field deselects after every character
# Description
While making a data map, on "stage 4" (Annotate), the user can customize the name of data labels. After each character is entered, the input field is deselected, so that I need to click again on the input field to type in another character

## Steps To Reproduce
1. Start creating a data map
2. proceed to step 4, annotate
3. type in a new name for a data column
4. see issue

## Expected behavior
user can type out a full word without interruptions 

## Actual behavior
after each character, the field is deselected, so it must be reselected in order to enter another character

https://github.com/techmatters/terraso-web-client/assets/86784/1d1a7958-3333-46ff-ae46-167a64de0074

### PR DESCRIPTION
**Pull request by josebui**
## Description

- Fixed drag and drop
- Fixed focus on popup on every key press

### Checklist
- [x] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
Fixes #1150

### CODE REVIEW

File: src/sharedData/visualization/components/VisualizationConfigForm/AnnotateStep.js [hunk 1]
```diff
@@ -82,6 +82,22 @@ const FORM_FIELDS = [
   },
 ];
 
+// Work around for react-beautiful-dnd issue. See: https://stackoverflow.com/a/75807063
```
Comment (paulschreiber) [inline src/sharedData/visualization/components/VisualizationConfigForm/AnnotateStep.js:85]: issue: please better describe "react-beautiful-dnd issue."

**Review by paulschreiber — APPROVED** [review]
