### PR TITLE
fix: use MUI properties to set share dialog width

### LINKED ISSUE #369: Not enough spacing between share buttons
## Description
There are no spaces between the share buttons using the "Share Landscape" feature.

Current
image

Figma Design
image

### PR DESCRIPTION
**Pull request by paulschreiber**
## Description
Increase width of social share dialog with MUI attributes/properties.

### Related Issues
Fixes #369.

### CODE REVIEW

File: src/common/components/SocialShare.js [hunk 1]
```diff
@@ -67,6 +67,8 @@ const SocialShare = ({ name }) => {
         onClose={handleClose}
         aria-labelledby="modal-modal-title"
         aria-describedby="modal-modal-description"
+        fullWidth={true}
```
Comment (josebui) [inline src/common/components/SocialShare.js:70]: Suggestion:
```suggestion
        fullWidth
```

**Review by josebui — APPROVED** [review]
